include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - lib/generated/**

linter:
  rules:
    prefer_const_constructors: true
    prefer_final_fields: true
    avoid_print: false
    sort_pub_dependencies: false
